# Generated by Django 2.0.1 on 2018-01-20 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('overall_sentiment', models.DecimalField(decimal_places=3, max_digits=5)),
                ('title', models.CharField(max_length=1000)),
                ('url', models.URLField(max_length=1000)),
            ],
            options={
                'verbose_name': 'ARTICLE',
                'verbose_name_plural': 'ARTICLES',
            },
        ),
        migrations.CreateModel(
            name='ArticleEntityAssoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.DecimalField(decimal_places=3, max_digits=5)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities_related', to='gotnews_app.Article')),
            ],
            options={
                'verbose_name': 'ARTICLEENTITYASSOC',
                'verbose_name_plural': 'ARTICLEENTITYASSOCS',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('occurrence_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ENTITY',
                'verbose_name_plural': 'ENTITIES',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'EVENT',
                'verbose_name_plural': 'EVENTS',
            },
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'NEWSSOURCE',
                'verbose_name_plural': 'NEWSSOURCES',
            },
        ),
        migrations.CreateModel(
            name='NewsSourceEntityAssoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.DecimalField(decimal_places=3, max_digits=5)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_sources_related', to='gotnews_app.Entity')),
                ('news_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities_related', to='gotnews_app.NewsSource')),
            ],
            options={
                'verbose_name': 'NEWSSOURCEENTITYASSOC',
                'verbose_name_plural': 'NEWSSOURCEENTITYASSOCS',
            },
        ),
        migrations.AddField(
            model_name='articleentityassoc',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_related', to='gotnews_app.Entity'),
        ),
        migrations.AddField(
            model_name='article',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_related', to='gotnews_app.Event'),
        ),
        migrations.AddField(
            model_name='article',
            name='news_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_related', to='gotnews_app.NewsSource'),
        ),
    ]
