# Generated by Django 2.0.1 on 2018-01-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotnews_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleentityassoc',
            name='sentiment',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='newssourceentityassoc',
            name='sentiment',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
    ]
