# Generated by Django 2.0.1 on 2018-01-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotnews_app', '0002_auto_20180121_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleentityassoc',
            name='article_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newssourceentityassoc',
            name='article_count',
            field=models.IntegerField(default=0),
        ),
    ]
