# Generated by Django 2.0.1 on 2018-01-21 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gotnews_app', '0003_auto_20180121_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleentityassoc',
            name='article_count',
        ),
        migrations.RemoveField(
            model_name='newssourceentityassoc',
            name='article_count',
        ),
    ]
